// babel.config.js — AUTO-GENERATED by AI Test Quality Agent
// Handles CommonJS and ES Modules (import/export).
// Requires: npm install --save-dev @babel/core @babel/preset-env babel-jest
module.exports = {
  presets: [
    ['@babel/preset-env', { targets: { node: 'current' }, modules: 'commonjs' }],
  ],
};
