// AUTO-GENERATED by AI Test Quality Agent
module.exports = {
  testEnvironment: "jsdom",
  setupFilesAfterEnv: ["@testing-library/jest-dom"],
  testMatch: ["**/tests/**/*.test.js"],
  transform: { "^.+\\.[jt]sx?$": "babel-jest" },
  transformIgnorePatterns: [
    "/node_modules/(?!(superagent|mapbox-gl)/)",
  ],
  moduleNameMapper: {
    "\\.(css|less|scss)$": "<rootDir>/__mocks__/styleMock.js",
    "^mapbox-gl$":           "<rootDir>/__mocks__/mapboxgl.js",
  },
  collectCoverageFrom: ["src/**/*.{js,jsx}", "!src/index.js"],
};
